development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_development
  pool: 5
  username: joshuarowley
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: sample_app_test
  pool: 5
  username: joshuarowley
  password:
cucumber:
  <<: *test